# Generated by Django 2.0.5 on 2018-06-01 12:55

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.management import create_permissions


def add_group_permissions(apps, schema_editor):

    for app_config in apps.get_app_configs():
        create_permissions(app_config, apps=apps, verbosity=0)

    group, created = Group.objects.get_or_create(name='admin')
    
    if created:
        view_order = Permission.objects.get(codename='view_order')
        group.permissions.add(view_order)
        group.save()

    
    # group, created = Group.objects.get_or_create(name='delivery') 
    # if created:
    #     group.permissions.add(can_change_order, can_view_order)
    #     logger.info('Delivery Group created')


    # group, created = Group.objects.get_or_create(name='customer') 
    # if created:
    #     group.permissions.add(can_view_order, can_add_order, can_change_order)
    #     logger.info('Customer Group created')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
