# Generated by Django 2.0.4 on 2018-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0002_snacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
