# Generated by Django 2.0.4 on 2018-04-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0003_locations_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snacks',
        ),
    ]
