# Generated by Django 2.0.4 on 2018-04-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0005_add_createion_update_delete_column_20180424_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Deleted',
            new_name='deleted',
        ),
    ]
