# Generated by Django 2.0.4 on 2018-04-25 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0006_auto_20180424_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_location', to='ordertakeouts.Locations'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='ordertakeouts.Users'),
        ),
    ]
