# Generated by Django 2.0.4 on 2018-04-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0007_auto_20180425_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_location', to='ordertakeouts.Locations'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='ordertakeouts.Users'),
        ),
        migrations.AlterModelTable(
            name='locations',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
