# Generated by Django 2.0.4 on 2018-04-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0008_auto_20180426_0440'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locations',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
