# Generated by Django 2.0.4 on 2018-05-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordertakeouts', '0009_change_table_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_location', to='ordertakeouts.Locations'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to='ordertakeouts.Users'),
        ),
    ]
